# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 417cee5b93b88dbfbe9bc52ba944965d9ad0538f560b6731e98c746fce63db0ddcf6309417333a0d505a6dca6d9306bee3e82ae2752661c3854a10ee4024ea2a

test:
  secret_key_base: 06a5f3bbaa59a9f6de6f55413171e05e01b5dac77b99494e86e8069b498cf120f5b17d8b526cdcd54907d85217d9a7bd9954d0760e280396e4bbae84d69def5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
